# Generated by Django 3.2.7 on 2021-12-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes_salida_materiaprima',
            name='producto',
        ),
        migrations.AddField(
            model_name='ordenes_salida_materiaprima',
            name='producto',
            field=models.ManyToManyField(to='operaciones.Materia_prima'),
        ),
    ]
